version: "3.2"

services:

  odoo:
    &odoo
    image: ${ODOO_IMAGE:-odoo}:${ODOO_IMAGE_VERSION:-latest}
    volumes:
      - "${CONTAINER_VOLUME?REQUIRED}/invoicing/odoo/extra-addons:/mnt/extra-addons:rw"
      - "${CONTAINER_VOLUME?REQUIRED}/invoicing/odoo/:/var/lib/odoo:rw"
      - "${PWD}/odoo/etc/:/etc/odoo:rw"
      - "${CONTAINER_VOLUME?REQUIRED}/invoicing/pg_socket:/var/run/postgresql"
    ports:
      - "8069:8069"
      - "8070:8072"
    environment:
      USER: "${ODOO_POSTGRES_USER:-odoo}"
      PASSWORD: "${ODOO_POSTGRES_PASSWORD:-odoo}"
      HOST: ${DB_HOST:-db}
      PORT: ${DB_PORT}
    command: --max-cron-threads 0 --workers 8 --log-handler=:INFO
    restart: on-failure
    logging:
      driver: 'awslogs'
      options:
        awslogs-region: 'eu-west-2'
        awslogs-group: '/var/log/odoo.log'

  odoo-cron:
    <<: *odoo
    ports:
      - "8072"
    command: --max-cron-threads 8 --no-xmlrpc --database ${ODOO_DATABASE:-uat}
    logging:
      driver: 'awslogs'
      options:
        awslogs-region: 'eu-west-2'
        awslogs-group: '/var/log/odoo-cron.log'

  keycloak:
    image: ${KEYCLOAK_IMAGE:-jboss/keycloak}:${KEYCLOAK_IMAGE_VERSION:-latest}
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD?REQUIRED}
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL:-WARN}
      PROXY_ADDRESS_FORWARDING: ${PROXY_ADDRESS_FORWARDING:-true}
      DB_ADDR: ${DB_HOST:-db}:${DB_PORT:-5432}
      DB_VENDOR: postgres
      DB_DATABASE: ${KEYCLOAK_DATABASE:-keycloak}
      DB_USER: ${KEYCLOAK_POSTGRES_USER:-keycloak}
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD:-keycloak}
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/keycloak/themes/gpit:/opt/jboss/keycloak/themes/gpit:rw"
    restart: on-failure
    logging:
      driver: 'awslogs'
      options:
        awslogs-region: 'eu-west-2'
        awslogs-group: '/var/log/keycloak.log'
